Sprint 2
kolosochek/middle.messenger.praktikum.yandex pull request #3
Opened 2022-11-30 07:02 UTC by kolosochek

2022-11-30 22:13 UTC, agadoev requested changes
Привет, @kolosochek , спасибо за работу

Почитай, пожалуйста, побольше про возможности typescript'a. Он дает гораздо больше возможностей, чем просто написание типов string, boolean и object. С помощью него нужно описывать систему так, чтобы при взгляде на код, было очевидно, как система устроена. Так же, ты можешь проверять себя, что TS помогает тебе предотвращать ошибки. Достаточно намеренно допустить ошибку в коде (например передать в функцию неправильный тип), и посмотретЬ, выдаст ли TS ошибку.

Понравилась реализация ShowModal, но ее так же можно улучшить с помощью TS

Давай поправим те комментарии, которые я оставил и двинемся дальше

2022-11-30 22:13 UTC, agadoev commented on src/components/ChatAsideProfile/index.ts
> +  events?: Record<string, never>
здесь лучше использовать [union type](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#union-type)
```suggestion
  events?: 'click' | 'hover' | и т.д.
```

2022-11-30 22:13 UTC, agadoev commented on src/components/ChatAsideSearch/style.module.less
> +      background: @shadow-color;
Круто, что вынес цвета в переменные 👍

2022-11-30 22:13 UTC, agadoev commented on src/components/ChatConversationList/index.ts
> +  activeChat?: object;
1. Когда ты описываешь тип, на самом деле, ты не просто задаешь тип для переменной, а ты декларативно описываешь систему. Посмотрев на тип, должно быть понятно, как устроена система. Сейчас я смотрю на ```activeChatId``` и не совсем понимаю, как он может быть типа boolean. Я бы предпочел оставить только string.
2. использование ```object``` не сильно отличается от использования any. Я предлагаю написать тип ```Conversation``` и использовать его вместо object

2022-11-30 22:13 UTC, agadoev commented on src/components/ChatReply/template.ts
> +</div>
Мне кажется или здесь должен быть ```</section>``` ?

2022-11-30 22:13 UTC, agadoev commented on src/components/ChatWindow/index.ts
> +  activeChat?: object;
давай опишем тип для activeChat

2022-11-30 22:13 UTC, agadoev commented on src/components/InputComponent/index.ts
> +    type?: string;
Для таких данных, как тип чего-то, ```string``` не очень подходит. Тип - это ограниченное количество значений. ```string``` допускает любые значения. Тут лучше подойдет использование union'a
```suggestion
  type?: "number" | "file";
```

2022-11-30 22:13 UTC, agadoev commented on src/components/InputComponent/index.ts
> +    required?: string;
по названию переменной я ожидаю, что тут будет ```boolean```

2022-11-30 22:13 UTC, agadoev commented on src/components/ProfileField/template.ts
> +        {{#if mode}}
я не очень понимаю, о чем свойство mode. По коду я вижу, что это какое-то условие. Тогда будет гораздо читаемее, если это свойство будет называться, как boolean. Например так
```suggestion
        {{#if withError}}
```

2022-11-30 22:13 UTC, agadoev commented on src/index.ts
> +        if (root) {
Тут довольно опасный момент. Если root не существует, страница не отрендерится и мы не получим никакой ошибки. У нас будет некорректное поведение и никакой информации об этом поведении. Лучше проверять root на null и генерировать исключение

2022-11-30 22:13 UTC, agadoev commented on src/index.ts
> +class Router {
1. Реализация роутера - задача следующего спринта. Хорошей инженерной практикой считается, когда в MR есть только тот код, который относится к задаче. Это упрощает жизнь как тебе, так и ревьеру.Ё
2. Если уж есть реализация роутера, то стоит ее вынести в отдельный файл, потому что сейчас совсем неочевидно, что в index.ts находится роутер

2022-11-30 22:13 UTC, agadoev commented on src/utils/Block.ts
> +        //
Закомментированный код лучше не держать в репозитории. Он загрязняет кодовую базу и отвлекает внимание.

2022-11-30 22:13 UTC, agadoev commented on src/utils/HTTPTransport.ts
> +    data?: Record<string, string>;
1. В data может быть вложенная структура данных, а не просто string: string. 
2. На уровне реализации HTTP логики, мы не должны знать о деталях реализации data. Там может быть что угодно, но нам не важно что. Я думаю, здесь отлично подошел бы тип unkown 

UPD. Когда оставлял комментарий к queryStringify, подумал, что возможно ты этим свойством хотел описать query-параметры. Если так, то можно оставить тип string: string, но переименовать свойство в query. Для POST запросов назвать свойство body и написать тип unknown

2022-11-30 22:13 UTC, agadoev commented on src/utils/HTTPTransport.ts
> +    }
Выглядит довольно сложно, я бы переписал вот так
```
public queryStringify(data: Record<string, string>) {
return "?" + Object
 .entries(data)
 .map(([key, value]) => `${key}=${value}`)
 .join("&")
}
```

2022-11-30 22:13 UTC, agadoev commented on src/views/ErrorView/index.ts
> +  mode?: string;
```suggestion
  mode?: 'Error500' | 'Error404' ;
```

2022-11-30 22:13 UTC, agadoev commented on src/utils/ShowModal.ts
> +        const modalWindowNode = document.querySelector('#modalwindow');
Тут можно так же добавить типы
```suggestion
        const modalWindowNode = document.querySelector<HTMLDivElement>('#modalwindow');
```

2022-12-01 07:06 UTC, kolosochek commented on src/components/ChatAsideProfile/index.ts
> +  events?: Record<string, never>
Привет! Спасибо за ревью, для меня это очень важно. TypeScript у меня откровенно слабоват, хотя я и JS никгда специально не изучал. Постараюсь это наверстать. 

Мне этот интерфейс тут вообщем то и не нужен, оставил его что бы была единая структура. По сути мне тут нужен пустой интерфейс ChatAsideProfileProps = {}, но по условиям спринта так делать нельзя.
заменил на 
events?: never; 

Наверное будет правильно создать новый тип, что то типа ComponentEventsType и туда через union добавлять все допустимые ивенты

type ComponentEventsType = 'click' | 'hover' | .. | never;
и потом уже в интерфейсе events?: ComponentEventsType;

2022-12-01 07:10 UTC, kolosochek commented on src/components/ChatConversationList/index.ts
> +  activeChat?: object;
1. Это с первого спринта осталось, мне тогда показалось клевой идеей хранить там false если нету активного чата и соответственно нет айдишника. Конечно string тут правильно, поправил у себя.
2. Абсолютно согласен, вот как переписал
```
type MessageType = {
    message: [
        author: string,
        time: string,
        date: string,
        text: string,
    ];
}

type ConversationType = {
    name: string,
    avatar_url: string,
    messages: MessageType[],
    unreadMessages: string,
    chat_id: string,
}

interface ChatConversationListProps {
  conversationList?: ConversationType[];
  activeChatId?: string;
  activeChat?: ConversationType;
}
```

2022-12-01 07:13 UTC, kolosochek commented on src/components/InputComponent/index.ts
> +    type?: string;
Интересная мысль, я об этом не подумал
`type?: "text" | "password" | "email" | "tel" |"number" | "file";`

2022-12-01 07:14 UTC, kolosochek commented on src/components/ChatReply/template.ts
> +</div>
Все верно, прошляпил закрывающий тег

2022-12-01 07:16 UTC, kolosochek commented on src/components/ChatWindow/index.ts
> +  activeChat?: object;
сделано

```
type MessageType = {
    message: [
        author: string,
        time: string,
        date: string,
        text: string,
    ];
}

type ConversationType = {
    name: string,
    avatar_url: string,
    messages: MessageType[],
    unreadMessages: string,
    chat_id: string,
}

interface ChatWindowProps {
  activeChat?: ConversationType;
}
```
Вынес общий тип в модель, отуда и экспортирую

2022-12-01 07:21 UTC, kolosochek commented on src/components/InputComponent/index.ts
> +    required?: string;
Это наследие из первого спринта, где я делал валидацию браузером через required и pattern, 
мне кажется что boolean тут был бы уместен если бы свойство было isRequired, в шаблоне это выглядит как 
`<input ... {{#if required}}required{{/if}} />`
Поменял на isRequired

2022-12-01 07:30 UTC, kolosochek commented on src/components/ProfileField/template.ts
> +        {{#if mode}}
Изначально были раздельные View для авторизации и регистрации, раздельные View для просмотра профиля, редактирования профиля и смены пароля. Потом я решил все эти View объединить в AuthView и ProfileView соответственно. 

При создании какого-то комплексного View, например ProfileView я в конструкторе передаю параметр mode, котоырый и выбирает по сути, что именно будет отображено на странице. Смотрим мы свойства профиля пользователя или редактируем.

Такую же логику я инкапсулировал в компонент InputComponent, если в конструкторе мы явно передаем режим в котором вьюха сейчас, то мы выдаем инпут, что бы пользователь мог его отредактировать и отправить какую-то форму. Иначе возвращаем обычный <p>Sometext</p>

По хорошему нужно объединить InputComponent и ProfileField[Component], у меня просто не хватило на это времени, боялся не сдать второй спринт в срок.

Тут по смыслу mode можно заменить на isInput

2022-12-01 07:34 UTC, kolosochek commented on src/index.ts
> +        if (root) {
Согласен, я привык после jQuery что можно сразу же проверять элемент, и он правильно приведется к типу boolean, поменял на 

`if (root !== null) { ... } else { throw new Error("There is no #root") }`

2022-12-01 07:34 UTC, kolosochek commented on src/utils/Block.ts
> +        //
Принято! Исправил

2022-12-01 07:38 UTC, kolosochek commented on src/index.ts
> +class Router {
Согласен, вынес роутер в отдельный класс и импортирую его в index

`import { Router } from "./utils/Router";

const router = new Router();

// router event listeners
window.addEventListener('DOMContentLoaded', router.route);
window.addEventListener('hashchange', router.route);
`

2022-12-01 07:41 UTC, kolosochek commented on src/utils/HTTPTransport.ts
> +    data?: Record<string, string>;
Принято, 
`data?: unknown;`

2022-12-01 07:48 UTC, kolosochek commented on src/utils/HTTPTransport.ts
> +    }
Беспардонно скопировал к себе ;D

2022-12-01 07:51 UTC, kolosochek commented on src/views/ErrorView/index.ts
> +  mode?: string;
Принято, поправил соответствующие интерфейсы в AuthView и ProfileView

2022-12-01 07:59 UTC, kolosochek commented on src/utils/ShowModal.ts
> +        const modalWindowNode = document.querySelector('#modalwindow');
Сначала не понял, а потом понял :)

2022-12-01 08:00 UTC, merged

2022-12-03 08:05 UTC, agadoev commented on src/components/ChatAsideProfile/index.ts
> +  events?: Record<string, never>
только never тут будет лишним, потому что и без never компилятор выдаст ошибку, если что-то другое передать. Never полезен, если нужно ограничить свойства объекта или реализовать [exhaustive switch](https://medium.com/technogise/type-safe-and-exhaustive-switch-statements-aka-pattern-matching-in-typescript-e3febd433a7a)

2022-12-03 08:08 UTC, agadoev commented on src/components/ChatConversationList/index.ts
> +  activeChat?: object;
спасибо! Стало лучше!
единственное, что отмечу - наверное слово Type в ConversationType лишнее, потому что дублируется информация о том, что это тип. Это как если бы мы каждую переменную именовали с постфиксом Variable.
У майкрософта, кстати, есть [стайлгайд] по typescript'y

2022-12-03 08:11 UTC, agadoev commented on src/components/ProfileField/template.ts
> +        {{#if mode}}
я понял. В таком случае, тут опять же можно сделать mode через union
```
mode: 'input' | 'auth' | 'profile' и тд
```

и в шаблоне проверять так
```
if mode === 'input'
```

причем нам компилятор TS'a сам подскажет значения mode и выдаст ошибку, если мы случайно опечатаемся

2022-12-03 08:12 UTC, agadoev commented on src/index.ts
> +        if (root) {
можно сделать проще

```
if (!root)
  throw new Error("There is no #root")
```